package uninstall

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/sageox/ox/internal/testguard"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAnalyzeHookFile_Unreadable(t *testing.T) {
	// nonexistent file should return error
	hasSageox, hasMixed, isEntireSox, err := analyzeHookFile("/nonexistent/path/hook")
	assert.Error(t, err)
	assert.False(t, hasSageox)
	assert.False(t, hasMixed)
	assert.False(t, isEntireSox)
}

func TestAnalyzeHookFile_AllMarkerTypes(t *testing.T) {
	tests := []struct {
		name       string
		content    string
		wantSageox bool
	}{
		{
			name:       "ox post-commit marker",
			content:    "#!/bin/sh\n# ox post-commit hook\necho done\n",
			wantSageox: true,
		},
		{
			name:       "ox prepare-commit-msg marker",
			content:    "#!/bin/sh\n# ox prepare-commit-msg hook\necho done\n",
			wantSageox: true,
		},
		{
			name:       "ox commit-msg marker",
			content:    "#!/bin/sh\n# ox commit-msg hook\necho done\n",
			wantSageox: true,
		},
		{
			name:       "Generated by ox marker",
			content:    "#!/bin/sh\n# Generated by ox\necho done\n",
			wantSageox: true,
		},
		{
			name:       "pre-commit.com in mixed hook",
			content:    "#!/bin/sh\n# ox pre-commit hook\nmake lint\n\n# pre-commit.com\npython hook\n",
			wantSageox: true,
		},
		{
			name:       "lint-staged in mixed hook",
			content:    "#!/bin/sh\n# ox pre-commit hook\nmake lint\n\n# lint-staged\nnpx lint-staged\n",
			wantSageox: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpFile := filepath.Join(t.TempDir(), "hook")
			require.NoError(t, os.WriteFile(tmpFile, []byte(tt.content), 0755))

			gotSageox, _, _, err := analyzeHookFile(tmpFile)
			require.NoError(t, err)
			assert.Equal(t, tt.wantSageox, gotSageox)
		})
	}
}

func TestAnalyzeHookFile_NonSageoxCodeBeforeMarker(t *testing.T) {
	// code before any sageox marker should be detected as mixed
	content := "#!/bin/sh\necho 'user code'\n# ox pre-commit hook\nmake lint\n"
	tmpFile := filepath.Join(t.TempDir(), "hook")
	require.NoError(t, os.WriteFile(tmpFile, []byte(content), 0755))

	hasSageox, hasMixed, isEntireSox, err := analyzeHookFile(tmpFile)
	require.NoError(t, err)
	assert.True(t, hasSageox)
	assert.True(t, hasMixed)
	assert.False(t, isEntireSox)
}

func TestRemoveRepoHooks_NoHooksDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	// no .git/hooks directory at all
	err := RemoveRepoHooks(tmpDir, false)
	assert.NoError(t, err)
}

func TestRemoveRepoHooks_DryRunMixed(t *testing.T) {
	tmpDir := t.TempDir()
	hooksDir := filepath.Join(tmpDir, ".git", "hooks")
	require.NoError(t, os.MkdirAll(hooksDir, 0755))

	// mixed hook should be reported but not modified in dry run
	content := "#!/bin/sh\n# husky\nnpm test\n\n# ox pre-commit hook\nmake lint\n"
	hookPath := filepath.Join(hooksDir, "pre-commit")
	require.NoError(t, os.WriteFile(hookPath, []byte(content), 0755))

	err := RemoveRepoHooks(tmpDir, true)
	require.NoError(t, err)

	// file should be unchanged
	got, err := os.ReadFile(hookPath)
	require.NoError(t, err)
	assert.Equal(t, content, string(got))
}

func TestRemoveSageoxSections_PreservesFilePermissions(t *testing.T) {
	// The whole test is about a POSIX mode surviving a rewrite; Windows
	// cannot express one, so there is no premise to assert against.
	testguard.RequirePOSIXPerms(t)
	tmpFile := filepath.Join(t.TempDir(), "hook")
	content := "#!/bin/sh\n# ox pre-commit hook\nmake lint\n\n\n# user section\necho done\n"
	require.NoError(t, os.WriteFile(tmpFile, []byte(content), 0755))

	err := removeSageoxSections(tmpFile)
	require.NoError(t, err)

	info, err := os.Stat(tmpFile)
	require.NoError(t, err)
	// verify executable bit preserved
	assert.NotEqual(t, os.FileMode(0), info.Mode()&0100, "owner execute bit should be preserved")
}

func TestRemoveSageoxSections_SectionEndAfterDoubleBlankLine(t *testing.T) {
	// sageox section followed by 2+ blank lines should end the section
	content := "#!/bin/sh\n# ox pre-commit hook\nmake lint\n\n\necho 'after double blank'\n"
	tmpFile := filepath.Join(t.TempDir(), "hook")
	require.NoError(t, os.WriteFile(tmpFile, []byte(content), 0755))

	err := removeSageoxSections(tmpFile)
	require.NoError(t, err)

	result, err := os.ReadFile(tmpFile)
	require.NoError(t, err)
	resultStr := string(result)

	assert.NotContains(t, resultStr, "# ox pre-commit hook")
	assert.NotContains(t, resultStr, "make lint")
	assert.Contains(t, resultStr, "echo 'after double blank'")
}

func TestRemoveSageoxSections_CommentAfterBlankEndsSection(t *testing.T) {
	// a comment after a blank line in a sageox section should end the section
	content := "#!/bin/sh\n# ox pre-commit hook\nmake lint\n\n# user comment\necho user\n"
	tmpFile := filepath.Join(t.TempDir(), "hook")
	require.NoError(t, os.WriteFile(tmpFile, []byte(content), 0755))

	err := removeSageoxSections(tmpFile)
	require.NoError(t, err)

	result, err := os.ReadFile(tmpFile)
	require.NoError(t, err)
	resultStr := string(result)

	assert.NotContains(t, resultStr, "# ox pre-commit hook")
	assert.NotContains(t, resultStr, "make lint")
	assert.Contains(t, resultStr, "# user comment")
	assert.Contains(t, resultStr, "echo user")
}

func TestRemoveSageoxSections_OtherToolMarkerEndsSageoxSection(t *testing.T) {
	// when inside a sageox section, hitting another tool marker should end the section
	content := "#!/bin/sh\n# ox pre-commit hook\nmake lint\n# lefthook\necho lefthook\n"
	tmpFile := filepath.Join(t.TempDir(), "hook")
	require.NoError(t, os.WriteFile(tmpFile, []byte(content), 0755))

	err := removeSageoxSections(tmpFile)
	require.NoError(t, err)

	result, err := os.ReadFile(tmpFile)
	require.NoError(t, err)
	resultStr := string(result)

	assert.Contains(t, resultStr, "#!/bin/sh")
	assert.NotContains(t, resultStr, "# ox pre-commit hook")
	assert.NotContains(t, resultStr, "make lint")
	assert.Contains(t, resultStr, "# lefthook")
	assert.Contains(t, resultStr, "echo lefthook")
}

func TestRemoveSageoxSections_NonexistentFile(t *testing.T) {
	err := removeSageoxSections("/nonexistent/path/hook")
	assert.Error(t, err)
}

func TestFindSageoxHooks_DirectoryEntries(t *testing.T) {
	// subdirectories in .git/hooks/ should be skipped
	tmpDir := t.TempDir()
	hooksDir := filepath.Join(tmpDir, ".git", "hooks")
	require.NoError(t, os.MkdirAll(filepath.Join(hooksDir, "subdir"), 0755))

	// also add a real hook so we verify subdir is skipped
	require.NoError(t, os.WriteFile(
		filepath.Join(hooksDir, "pre-commit"),
		[]byte("#!/bin/sh\n# ox pre-commit hook\nmake lint\n"),
		0755,
	))

	items, err := FindSageoxHooks(tmpDir)
	require.NoError(t, err)
	assert.Len(t, items, 1)
	assert.Equal(t, "pre-commit", items[0].Name)
}
